
PROGS := smallSort isPrime fallDistance isPalindrome hailstone


all: $(PROGS)

smallSort: smallSort.cpp
	g++ -g smallSort.cpp -o smallSort

isPrime: isPrime.cpp
	g++ -g isPrime.cpp -o isPrime

fallDistance: fallDistance.cpp
	g++ -g fallDistance.cpp -o fallDistance

isPalindrome: isPalindrome.cpp
	g++ -g isPalindrome.cpp -o isPalindrome

hailstone: hailstone.cpp
	g++ -g hailstone.cpp -o hailstone


clean:
	rm -f $(PROGS) *.o *~