
PROGS := revPrint recSum hailstone2 convert

all: $(PROGS)


revPrint: revPrint.cpp
	g++ -g revPrint.cpp -o revPrint

recSum: recSum.cpp
	g++ -g recSum.cpp -o recSum

hailstone2: hailstone2.cpp
	g++ -g hailstone2.cpp -o hailstone2

convert: convert.cpp
	g++ -g convert.cpp -o convert


clean:
	rm -f $(PROGS) *.o *~
