PROGS := matterState rangeSum maxMin numGuess fileAdder

all: $(PROGS)

matterState: matterState.cpp
	g++ -g matterState.cpp -o matterState

rangeSum: rangeSum.cpp
	g++ -g rangeSum.cpp -o rangeSum

maxMin: maxMin.cpp
	g++ -g maxMin.cpp -o maxMin

numGuess: numGuess.cpp
	g++ -g numGuess.cpp -o numGuess

fileAdder: fileAdder.cpp
	g++ -g fileAdder.cpp -o fileAdder


clean:
	rm -f $(PROGS) *.o *~